name: Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish latest
    uses: ./.github/workflows/publish-latest.yml
    secrets: inherit
